print(type(int('25')), int('25'))
print(type(int(3.14)), int(3.14))
print(type(int(True)), int(True))
print(type(int(False)), int(False))

print(type(float('2.34')), float('2.34'))
print(type(float('20')), float('20'))
print(type(float(25)), float(25))
print(type(float(True)), float(True))
print(type(float(False)), float(False))

# str()
# list()
# tuple()
# set()
# frozenset()
# dict()
